### ISSUE TITLE
Error: NetCDF: Name contains illegal characters

### ISSUE THREAD

**Issue by psbecker** [NOAA-OWP/noah-owp-modular#111]
I got Noah-OWP to compile using Windows Subsystem for Linux, but after typing 
`cd run/
./noah_owp_modular.exe namelist.input`
I get the following:
` Initializing...
 time var def error: NetCDF: Name contains illegal characters
 Running...
 Finalizing...
 Finished!`
 And the output.nc file ends up missing a bunch of information. I see that line 90 of the OutputModule.f90 has `call check (nf90_def_var(ncid, "time", NF90_DOUBLE, (/time_dim/), time_id), "time var def error", iret); if (iret /= 0) return   ! with error checking`
 But I don't know where or what the actual issue is.

**Comment by SnowHydrology** [comment]
@psbecker, This sounds like it may be an issue with your NetCDF install or file paths. For future reference, please provide additional information on your errors to make them as reproducible as possible.
