### ISSUE TITLE
emitted longwave <0; skin T may be wrong due to inconsistent

### ISSUE THREAD

**Issue by psbecker** [NOAA-OWP/noah-owp-modular#112]
Hi all, 
I'm trying to run the noah-owp-modular with my own forcing data for a different basin (one in Utah) and got the following message. Additionally, I tried opening the output.nc file for it and the output times give me the year 2038. I'm quite unsure how to address the below issue as my longwave radiation is never less than 0. Any ideas? I'm attaching the forcing file with the formatted text. I wonder if anyone could run the modular with it and let me know if they're getting the same error?
[moonlake_input.dat.zip](https://github.com/user-attachments/files/16167814/moonlake_input.dat.zip)

`Initializing...
 Running...
 emitted longwave <0; skin T may be wrong due to inconsistent
 input of SHDFAC with LAI
  2147483647  2147483647 SHDFAC=  0.699999988     parameters%VAI=   4.65493155     TV=  -41113.3789     TG=   36346.2188    
 LWDN=   245.940002     energy%FIRA=  -4.16523674E+09 wa
[moonlake_input.dat.zip](https://github.com/user-attachments/files/16167771/moonlake_input.dat.zip)
ter%SNOWH=   0.00000000    
 Exiting ...
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_OVERFLOW_FLAG IEEE_UNDERFLOW_FLAG`

**Comment by aaraney** [comment]
Hey @psbecker, you might look into [this issue thread](https://github.com/NOAA-OWP/DMOD/issues/472#issuecomment-1912250249). Not certain your issue is a result of the same problem, but they seem similar.

**Comment by SnowHydrology** [comment]
@psbecker We support and maintain Noah-OM for use in the NextGen framework. In our internal evaluations (as @aaraney  has pointed out), we have found this error to be triggered as a result of forcing data errors and namelist conflicts. Unfortunately, we cannot evaluate your data formatting, datetime strings, namelist options, etc. Best of luck!
