### ISSUE TITLE
Documentation suggestions and example step-by-step instructions

### ISSUE THREAD

**Issue by rlmcdaniel** [NOAA-OWP/noah-owp-modular#24]
Suggestions/Questions:
1.  output.nc --> define the output variables
2.  Describe what the different directories/files contain
3.  Passed by reference documentation - What was done when a variable pbr name change was detected?  Which variable names were chosen for use in Modular Noah-MP?  -- basically the documentation seems incomplete, stopping after the detection and not continuing with what was done after.

I have also included a set of more detailed instructions for the current 'full' noah-mp-modular.
[Step_by_step_instructions-Modular_NOAH-MP_full_directory.docx](https://github.com/NOAA-OWP/noah-mp-modular/files/7210354/Step_by_step_instructions-Modular_NOAH-MP_full_directory.docx)

**Comment by andywood** [comment]
A good place for the useful material in the word document would be the
repo's wiki tab.  It would be easier to update and convenient for users to
view without having to download a document.  An example of this (related to
compilation) for summa is here:
https://github.com/CH-Earth/summa/wiki/SUMMA-Makefile-Part-0-configuration

**Comment by rlmcdaniel** [comment]
I added the step by step instructions to the wiki as a tutorial.  I will need to add the info under Additional Modules once changes to the repo have been made.
