### ISSUE TITLE
Rename noah-mp-modular

### ISSUE THREAD

**Issue by andywood** [NOAA-OWP/noah-owp-modular#27]
There are significant concerns over the similarity between the current name and 'Noah-MP', which is well-known in its community and has a code base / repo in another organization, NCAR.  Right now, the parent code of Noah-MP exists as 'NoahLSM' at EMC -- https://github.com/NOAA-EMC/NoahLSM -- which does not apparently raise concerns about similarity.  

The code contents and functionality will likely diverge steadily from the original Noah-MP components, and will not be backward compatible or ultimately closely related to Noah-MP; though it will always be a model that is from the Noah model tree (which began as the OSU model).  Similarly the Stanford Watershed Model from the 1960s later spawned other models such as EPA's HSPF and the NWS Sacramento model, which took on other names. I suggest a name that includes 'Noah' to recognize the heritage, but not 'Noah-MP', which may soon be trademarked.  

This re-branding will avoid confusion in talking about Noah-MP versus, say, 'Noah-modular' even during the development stage.

**Comment by SnowHydrology** [comment]
Consider the following names, in no particular order (also can be hyphenated or not):

- Noah-BMI
- Noah-Modular
- Noah-Mod
- Noah-Next
- Noah-Plus
- Open-Noah
- NoahFlex
- NoahOPT
- NoahEXT
- Noah-OWP
- NoahNWM
- Noah-NOAA

**Comment by SnowHydrology** [comment]
Name change to Noah-OWP-Modular is now reflected in URL.
