### ISSUE TITLE
Include error handling for out-of-range options

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/noah-owp-modular#58]
There is currently no internal error handling for out-of-range options in Noah-OWP-Modular. This means we can enter a non-sensical value for an option flag and the model would still try to run without alerting us of an issue.

We should implement code, likely in `NamelistRead.f90` that checks each option to make sure the provided value is within a valid range. If the option is not in range, then the model should stop running and return a clear message. In pseudo code:

```
if option_val < 0 or option_val > option_max then
    print "option_val for option_name out of range, exiting..."
    stop
end if
```

**Comment by nmizukami** [comment]
Hi Kieth, I can work on this. It would be good for me to get back to this and this should not be difficult change.

**Comment by SnowHydrology** [comment]
Thanks @nmizukami, that would be great! You had mentioned on the call building a module for error handling (maybe something like `ErrorHandling.f90`?) I was thinking that could be useful so we could call the error routine multiple times:

```
call ErrorModule(option_val, option_min, option_max, param_name)
``` 

The module could determine if `option_val` is valid based on `min` and `max` and then print an error that also gives the param name if it's not valid.

**Comment by nmizukami** [comment]
I was thinking about general usage  like this (also use for case statement that determines model option, but can be used for other error check)

```
subroutine sys_abort(err, message)
  implicit none
  integer, intent(in) :: err                  ! error code
  character(*), intent(in) :: message         ! error message
  if(err/=0)then
    write(*, '(A)') 'FATAL ERROR: '//trim(message)
    call flush(6)
    stop
  endif
subroutine
```

then if opt is not select case, this can be called like. 

```
select case(options%OPT_SNF)
  case(1)
  ....
  case(2,3,5,6)
  ...
  case(4)
  ....
  case(7)
  ...
  default case; ierr=1; call sys_abort(ierr, 'option for precipitation phase partitioning method not valid')
end select
```

error code may not be needed, but some of fortran intrinsic routines (e.g., open, allocate) can output error code, which is useful to detect error.  you can elaborate the error in details.

**Comment by SnowHydrology** [comment]
I like that suggestion, @nmizukami, but I was also thinking it might be more efficient and intuitive to put the error handling where the options get read (`NamelistRead.f90`). The model shouldn't continue running if invalid option values are read in.

**Comment by nmizukami** [comment]
Hi Kieth,  yes checking in NamelistRead.f90 make sense to me!
