### ISSUE TITLE
Make NamelistRead more better

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/noah-owp-modular#61]
@lcunha0118 noticed that you can run Noah-OWP-Modular with a namelist file that's missing entries. To test this, I ran the model through `initialize()` and printed out results of the `terrain_slope` parameter. 

- Scenario 1 (correct namelist): Model initializes, namelist and parameter have same correct value (10°)
![image](https://user-images.githubusercontent.com/32177682/183754913-8e1d3995-a7f4-4567-9989-8e8fe9da58b3.png)
- Scenario 2 (namelist missing terrain_slope): Model initializes, namelist and parameter have same zero value 
![image](https://user-images.githubusercontent.com/32177682/183755007-50dd308e-7def-4203-8258-d980d2524152.png)
- Scenario 3 (namelist missing terrain_slope with fake entry added in its place): Model crashes, error is reported
![image](https://user-images.githubusercontent.com/32177682/183755055-a3088350-32af-48df-bc18-7d154fbaa853.png)

We should implement a routine that stops the model from running when a namelist key is missing, similar to the error that's reported when an incorrect key is provided.

**Comment by andywood** [comment]
Happy to fix this ... the namelist_read routines are pretty standard so
it's after that that the error checking comes.
I can add something to make sure the keys found = the length of the
namelist data structure so that if people add namelist options later,
there's no custom updating of the entry check.

**Comment by SnowHydrology** [comment]
Thanks, @andywood, that would be great! Is there a way to identify and print which of the keys are missing? Something like: `NamelistRead error: Missing terrain_slope value`

**Comment by zhengtaocui** [comment]
Are any of the keys optional? It looks like things are getting complicated when there are dependencies between the keys. For example, soil_depth is only needed when structure_option is 2.

**Comment by SnowHydrology** [comment]
That's a good observation @zhengtaocui. @andywood noticed the structure_option isn't strictly necessary. If you want all layers to have the same thickness, you can just give them the same thickness (no extra option needed).

**Comment by andywood** [comment]
This should be resolved by PR 64.  Checks for both missing and incorrect keys and exits if there's a problem.

**Comment by andywood** [comment]
Not currently.  I'm simplifying this too -- wiped out the structure option
just now ... I'll do a push on the new namelist read soon.

**Comment by SnowHydrology** [comment]
Closed by #62 and #63
