### ISSUE TITLE
Generating NoahOWPModular configuration files from hydrofabric linked data

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/noah-owp-modular#69]
I am trying to generate noah owp modular configuration files from linked data in the hydrofabric, specifically the `cfe_noahowp_attributes` table. The generated config files will be used to run noah owp modular using NGEN. For reference, I am using [hydrofabric v1.2](https://nextgen-hydrofabric.s3.amazonaws.com/index.html#v1.2/). Having used the `cfe_noahowp_attributes` schema outlined [here](https://mikejohnson51.github.io/hyAggregate/#Hydrologic_Model_Attributes), looked through the [fortran option source](https://github.com/NOAA-OWP/noah-owp-modular/blob/30d0f53e8c14acc4ce74018e06ff7c9410ecc13c/src/OptionsType.f90#L9) code, and referred to the [example namelist in `/run`](https://github.com/NOAA-OWP/noah-owp-modular/blob/30d0f53e8c14acc4ce74018e06ff7c9410ecc13c/run/namelist.input) as a guidance, i've determined most of the "mappings", but I am not sure how to generate the below configuration options. Sane defaults to any of these options or derivations from other attributes would also suffice! Thanks for the help in advance!

Configuration options in question:

- `forcing.rain_snow_thresh` - rain-snow temperature threshold (degrees Celcius)
- `structure.soilcolor` - soil color code
- `initial_values.dzsnso` - level thickness [m]
- `initial_values.sice` - initial soil ice profile [m3/m3]
- `initial_values.sh2o` - initial soil liquid profile [m3/m3]
- `initial_values.zwt` - initial water table depth below surface

To hopefully make this a little easier, here is the Hydrofabric v1.2 [`cfe_noahowp_attributes` schema](https://mikejohnson51.github.io/hyAggregate/#Hydrologic_Model_Attributes) i've been using as reference:

| Tables | Description Layer(s) | Summary Function | Source |
|--------|----------------------|------------------|--------|
| bexp | Beta Parameter 4 | mode | soilproperties_CONUS_FullRouting.nc |
| IVGTYP | Dominant category 1 | mode | wrfinput_CONUS.nc |
| ISLTYP | Dominant category 1 | mode | wrfinput_CONUS.nc |
| dksat | Saturated Soil Connectivity 4 | geometric mean | soilproperties_CONUS_FullRouting.nc |
| psisat | Saturated soil matric potential 4 | geometric mean | soilproperties_CONUS_FullRouting.nc |
| slope | Slope Index 1 | mean | soilproperties_CONUS_FullRouting.nc |
| smcmax | Saturated value of soil moisture [volumetric] 4 | mean | soilproperties_CONUS_FullRouting.nc |
| smcwlt | Wilting point soil moisture [volumetric] 4 | mean | soilproperties_CONUS_FullRouting.nc |
| refkdt | Parameter in the surface runoff parameterization 1 | mean | soilproperties_CONUS_FullRouting.nc |
| cwpvt | Empirical canopy wind parameter 1 | mean | soilproperties_CONUS_FullRouting.nc |
| vcmx25 | Maximum rate of carboxylation at 25 C [ umol CO2/m2/s] 1 | mean | soilproperties_CONUS_FullRouting.nc |
| mp | Slope of Conductance to photosynthesis relationship 1 | mean | soilproperties_CONUS_FullRouting.nc |
| mfsno | Snowmelt m parameter 1 | mean | soilproperties_CONUS_FullRouting.nc |
| Coef | Coefficient 1 | mean | GWBUCKPARM_CONUS_FullRouting.nc |
| Zmax | Zmax 1 | mean | GWBUCKPARM_CONUS_FullRouting.nc |
| Expon | Exponent 1 | mode | GWBUCKPARM_CONUS_FullRouting.nc |

Also worth noting, `IVGTYP`'s are the USGS 27 code variant and `ISLTYP` comes from `STAS`.

**Comment by SnowHydrology** [comment]
Closed with`ngen_cal` [PR86](https://github.com/NOAA-OWP/ngen-cal/pull/86).
