### ISSUE TITLE
Remove hard-coding of x and y dimensions from RunModule.f90

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/noah-owp-modular#72]
https://github.com/NOAA-OWP/noah-owp-modular/blob/8161eab9a3f8f99694ec062a92cd3b21da7e806d/src/RunModule.f90#L87

For testing, we hard-coded these values, but this will get superseded by NetCDF read functionalities in the gridded driver.

**Comment by GreyEvenson-NOAA** [comment]
PR #85 removed hard-coding of gridded spatial dimensions. They are now read-into the model via the NetCDF input file.
