### ISSUE TITLE
Test if constant values need to be transferred from grid to column and back

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/noah-owp-modular#76]
Noah-OWP-Modular has some constant variables that go through the same transfer process as the time-/space-varying variables. Test if this still needs to be done. If not, remove variables from the transfer routines that occur each timestep.

Example: https://github.com/NOAA-OWP/noah-owp-modular/blob/a39c372f3c61f05e574943e245839d683aa35e4f/src/ParametersGridType.f90#L81

Related to #5

**Comment by GreyEvenson-NOAA** [comment]
@SnowHydrology, I believe this issue was mostly addressed by PR #82 though I think we could further reduce unnecessary transfers by implementing the ConstantsModule (i.e., Issue #5). Would you recommend closing this issue or do you see value in keeping it alive?
