### ISSUE TITLE
Namelist options are not reflecting in the NextGen Output

### ISSUE THREAD

**Issue by aniketgupta2009** [NOAA-OWP/noah-owp-modular#79]
Hi,

I am interested to test different module options of Noah-MP under NextGen Framework. I tried to change some options in the namelist but it is not reflected in the NextGen Framework output.

Please let me know how can I control the CFE+NoahMP configuration using name list options. Also, I do not see any spin-up options and I would also like to output different NoahMP variables in NextGen output.

Thanks

**Comment by SnowHydrology** [comment]
Hello @aniketgupta2009,

Can you provide some more information? 

As of now, Noah-MP is not configured with BMI to run in the NextGen framework. This refactored version with BMI is Noah-OWP-Modular. 

Which options were you changing in the namelist and how were they not being reflected in NextGen output?

The combination of CFE and Noah-OWP-Modular is controlled by the NextGen [realization](https://github.com/NOAA-OWP/ngen/blob/master/data/example_bmi_multi_realization_config_w_noah_pet_cfe.json) file, not by the Noah-OWP-Modular namelist. 

What do you mean by spin-up options? (Noah-OWP-Modular and Noah-MP are column models—most available spin-up options are parts of frameworks like HRLDAS or WRF-Hydro.)

To output different variables, they need to be added to the [BMI specification](https://github.com/NOAA-OWP/noah-owp-modular/blob/main/bmi/bmi_noahowp.f90).

Thanks for reaching out.

**Comment by aniketgupta2009** [comment]
Hi Keith,

Thank you so much for you your response and clarification.

I am actually interested in using different vegetation options from Noah-OWP-Modular under NextGen Framework.

I used this realization file on the test case (https://github.com/NOAA-OWP/ngen/blob/master/data/example_bmi_multi_realization_config.json):
[test_realization.txt](https://github.com/NOAA-OWP/noah-owp-modular/files/12346391/test_realization.txt)

I tried to change the vegetation option in Noah-OWP namelist but it is not reflecting in the NextGen output as you explained (https://github.com/NOAA-OWP/noah-owp-modular/blob/30d0f53e8c14acc4ce74018e06ff7c9410ecc13c/run/namelist.input).

Is there any way where I can see changes in NextGen output once I change the schemes of Noah-OWP-Modular? I am also interested in some outputs like LAI, Transpiration etc. For now, I do not know how to control the outputs in the realization file.

Thanking You.

Aniket

**Comment by aniketgupta2009** [comment]
Hi Keith,

I just realised that the Noah-OWP-Modular does not have any plant phenology.

Also, I notice that there is no spinup option for NextGen Framework.

 Could you please clarify for me on my this comment and the old comment?

Thanking You.

Aniket
